http:
  middlewares:
    oidc-auth:
      plugin:
        traefik-oidc-auth:
          Provider:
            Url: ...
            ClientId: ...
            ClientSecret: ...
          LogLevel: DEBUG
          BypassAuthenticationRule: PathPrefix(`/client`)
          Scopes:
            - openid
            - profile
            - email
          SessionCookie:
            Secure: false